/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnow_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API

#import "GTLAtnowConstants.m"

#import "GTLAtnowUserDetail.m"
#import "GTLAtnowUserDetailCollection.m"

#import "GTLQueryAtnow.m"
#import "GTLServiceAtnow.m"
