/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnow.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API

#import "GTLAtnowConstants.h"

#import "GTLAtnowUserDetail.h"
#import "GTLAtnowUserDetailCollection.h"

#import "GTLQueryAtnow.h"
#import "GTLServiceAtnow.h"
