/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowUserDetailCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowUserDetailCollection (0 custom class methods, 1 custom properties)

#import "GTLAtnowUserDetailCollection.h"

#import "GTLAtnowUserDetail.h"

// ----------------------------------------------------------------------------
//
//   GTLAtnowUserDetailCollection
//

@implementation GTLAtnowUserDetailCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLAtnowUserDetail class]
  };
  return map;
}

@end
