/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowUserDetail.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowUserDetail (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAtnowUserDetail
//

@interface GTLAtnowUserDetail : GTLObject
@property (nonatomic, copy) NSString *eduEmail;
@property (nonatomic, retain) NSNumber *numRatings;  // intValue
@property (nonatomic, retain) NSNumber *rating;  // floatValue
@property (nonatomic, copy) NSString *userId;
@end
