/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryAtnow.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAtnow (3 custom class methods, 2 custom properties)

#import "GTLQueryAtnow.h"

#import "GTLAtnowUserDetail.h"
#import "GTLAtnowUserDetailCollection.h"

@implementation GTLQueryAtnow

@dynamic fields, Id;

#pragma mark - "users" methods
// These create a GTLQueryAtnow object.

+ (instancetype)queryForUsersGetUserByIdWithId:(NSString *)Id {
  NSString *methodName = @"atnow.users.getUserById";
  GTLQueryAtnow *query = [self queryWithMethodName:methodName];
  query.Id = Id;
  query.expectedObjectClass = [GTLAtnowUserDetail class];
  return query;
}

+ (instancetype)queryForUsersInsertWithObject:(GTLAtnowUserDetail *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"atnow.users.insert";
  GTLQueryAtnow *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAtnowUserDetail class];
  return query;
}

+ (instancetype)queryForUsersListUsers {
  NSString *methodName = @"atnow.users.listUsers";
  GTLQueryAtnow *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAtnowUserDetailCollection class];
  return query;
}

@end
