/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryAtnow.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAtnow (3 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAtnowUserDetail;

@interface GTLQueryAtnow : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *Id;

#pragma mark - "users" methods
// These create a GTLQueryAtnow object.

// Method: atnow.users.getUserById
//  Authorization scope(s):
//   kGTLAuthScopeAtnowUserinfoEmail
// Fetches a GTLAtnowUserDetail.
+ (instancetype)queryForUsersGetUserByIdWithId:(NSString *)Id;

// Method: atnow.users.insert
//  Authorization scope(s):
//   kGTLAuthScopeAtnowUserinfoEmail
// Fetches a GTLAtnowUserDetail.
+ (instancetype)queryForUsersInsertWithObject:(GTLAtnowUserDetail *)object;

// Method: atnow.users.listUsers
//  Authorization scope(s):
//   kGTLAuthScopeAtnowUserinfoEmail
// Fetches a GTLAtnowUserDetailCollection.
+ (instancetype)queryForUsersListUsers;

@end
