/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API

#import "GTLAtnowConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAtnowUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
