/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowPoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowPoint (0 custom class methods, 3 custom properties)

#import "GTLAtnowPoint.h"

// ----------------------------------------------------------------------------
//
//   GTLAtnowPoint
//

@implementation GTLAtnowPoint
@dynamic location, x, y;
@end
