/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowTaskCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowTaskCollection (0 custom class methods, 1 custom properties)

#import "GTLAtnowTaskCollection.h"

#import "GTLAtnowTask.h"

// ----------------------------------------------------------------------------
//
//   GTLAtnowTaskCollection
//

@implementation GTLAtnowTaskCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLAtnowTask class]
  };
  return map;
}

@end
