/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowTask.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowTask (0 custom class methods, 11 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAtnowPoint;
@class GTLAtnowUserDetail;

// ----------------------------------------------------------------------------
//
//   GTLAtnowTask
//

@interface GTLAtnowTask : GTLObject
@property (nonatomic, copy) NSString *category;
@property (nonatomic, retain) NSNumber *completed;  // boolValue

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (nonatomic, copy) NSString *descriptionProperty;

@property (nonatomic, retain) NSNumber *expiration;  // longLongValue
@property (nonatomic, retain) NSNumber *price;  // floatValue
@property (nonatomic, retain) GTLAtnowUserDetail *requester;
@property (nonatomic, retain) GTLAtnowPoint *requesterLocation;
@property (nonatomic, retain) NSNumber *taskId;  // longLongValue
@property (nonatomic, copy) NSString *taskLocation;
@property (nonatomic, retain) NSNumber *timeRequested;  // longLongValue
@property (nonatomic, copy) NSString *title;
@end
