/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowTask.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowTask (0 custom class methods, 11 custom properties)

#import "GTLAtnowTask.h"

#import "GTLAtnowPoint.h"
#import "GTLAtnowUserDetail.h"

// ----------------------------------------------------------------------------
//
//   GTLAtnowTask
//

@implementation GTLAtnowTask
@dynamic category, completed, descriptionProperty, expiration, price, requester,
         requesterLocation, taskId, taskLocation, timeRequested, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"descriptionProperty" : @"description"
  };
  return map;
}

@end
