/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowUserDetail.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowUserDetail (0 custom class methods, 4 custom properties)

#import "GTLAtnowUserDetail.h"

// ----------------------------------------------------------------------------
//
//   GTLAtnowUserDetail
//

@implementation GTLAtnowUserDetail
@dynamic eduEmail, numRatings, rating, userId;
@end
