/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAtnowPoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLAtnowPoint (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAtnowPoint;

// ----------------------------------------------------------------------------
//
//   GTLAtnowPoint
//

@interface GTLAtnowPoint : GTLObject
@property (nonatomic, retain) GTLAtnowPoint *location;
@property (nonatomic, retain) NSNumber *x;  // doubleValue
@property (nonatomic, retain) NSNumber *y;  // doubleValue
@end
