/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryAtnow.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAtnow (2 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAtnowTask;

@interface GTLQueryAtnow : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *category;
@property (nonatomic, copy) NSString *filter;
@property (nonatomic, copy) NSString *limit;
@property (nonatomic, copy) NSString *price;

#pragma mark - "tasks" methods
// These create a GTLQueryAtnow object.

// Method: atnow.tasks.insert
//  Authorization scope(s):
//   kGTLAuthScopeAtnowUserinfoEmail
// Fetches a GTLAtnowTask.
+ (instancetype)queryForTasksInsertWithObject:(GTLAtnowTask *)object;

// Method: atnow.tasks.list
//  Optional:
//   category: NSString
//   filter: NSString
//   limit: NSString
//   price: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAtnowUserinfoEmail
// Fetches a GTLAtnowTaskCollection.
+ (instancetype)queryForTasksList;

@end
