/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryAtnow.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   atnow/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAtnow (2 custom class methods, 5 custom properties)

#import "GTLQueryAtnow.h"

#import "GTLAtnowTask.h"
#import "GTLAtnowTaskCollection.h"

@implementation GTLQueryAtnow

@dynamic category, fields, filter, limit, price;

#pragma mark - "tasks" methods
// These create a GTLQueryAtnow object.

+ (instancetype)queryForTasksInsertWithObject:(GTLAtnowTask *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"atnow.tasks.insert";
  GTLQueryAtnow *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAtnowTask class];
  return query;
}

+ (instancetype)queryForTasksList {
  NSString *methodName = @"atnow.tasks.list";
  GTLQueryAtnow *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAtnowTaskCollection class];
  return query;
}

@end
